//! T51: the front page is a consequence of the fleet, not an administration.
//!
//! Homepage listed every service by hand in `services.yaml`, and on
//! 2026-09-01 that file was zero bytes — every config file under
//! `homepage-config/` held not a single entry. The page answered 200 and
//! showed nothing, which is why nobody noticed: an empty dashboard looks
//! exactly like a dashboard with nothing wrong.
//!
//! The same shape as T1 and T2: the orchestrator already knows every stack
//! and every route it wrote, so the page is rendered rather than maintained,
//! and a new stack cannot be missing from it.
//!
//! What is listed is the ROUTES — the names Kenny actually types — rather
//! than internal addresses. A service without a route is not on the front
//! page, which is correct: the front page is the front door.

/// One entry: the app it belongs to and the hostname its route matches.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Entry {
    pub app: String,
    pub host: String,
}

/// Pull `(router-name, hostname)` out of a Traefik route fragment.
///
/// A line scanner rather than a yaml parse, for the same reason the
/// `/appdata` check next to it is one: these files are written by this
/// program from a template, and the two agree about what a route looks like.
pub fn entries_from_route(content: &str) -> Vec<Entry> {
    let mut out = Vec::new();
    let mut app = String::new();
    for line in content.lines() {
        let t = line.trim();
        if t.starts_with('#') || t.is_empty() {
            continue;
        }
        // `    name:` under routers — four spaces, no space in the key.
        let indent = line.len() - line.trim_start().len();
        if indent == 4 && t.ends_with(':') && !t.contains(' ') {
            app = t.trim_end_matches(':').to_string();
            continue;
        }
        if let Some(rest) = t.strip_prefix("rule:") {
            if let Some(h) = rest.split('`').nth(1) {
                if !app.is_empty() && h.contains('.') {
                    out.push(Entry {
                        app: app.clone(),
                        host: h.to_string(),
                    });
                }
            }
        }
    }
    out
}

/// Render Homepage's `services.yaml` for the whole fleet.
///
/// One group per stack, in the order given, and the apps within a stack in
/// the order their routes appear. Stable output, so a deploy that changes
/// nothing writes a byte-identical file and the push reports "unchanged".
///
/// A stack with no routes is skipped entirely rather than rendered as an
/// empty group: an empty heading on a dashboard reads as "this is broken"
/// when it means "this has no front door".
pub fn services_yaml(stacks: &[(String, Vec<Entry>)]) -> String {
    let mut out = String::from(
        "# Generated by the homelab orchestrator — every stack that has a\n\
         # gateway route appears here. Edits are overwritten on the next\n\
         # deploy; change the stack's route file instead.\n\
         #\n\
         # T51: this file was 0 bytes until 2026-09-01, so the front page\n\
         # rendered and listed nothing.\n",
    );
    for (stack, entries) in stacks {
        if entries.is_empty() {
            continue;
        }
        out.push_str(&format!("\n- {}:\n", stack));
        for e in entries {
            out.push_str(&format!(
                "    - {}:\n        href: https://{}/\n        siteMonitor: https://{}/\n",
                e.app, e.host, e.host
            ));
        }
    }
    out
}
