//! C1/C2 · one log shipper per container, and it is not promtail any more.
//!
//! Promtail reached end of life on 2 March 2026 — Grafana's own words:
//! "Commercial support has ended. No future support or updates will be
//! provided." Eleven containers here ran it, and two ran nothing at all
//! because they have no docker and therefore never got the sidecar every
//! other stack has (F245, F249).
//!
//! Kenny chose Alloy on the two native containers and then all eleven others
//! (form C1/C2, 2026-09-02). This module generates the configuration; the
//! deploy installs the package.
//!
//! **Why apt and not a binary.** Alloy ships a `.deb`, and this fleet already
//! installs `prometheus-node-exporter` that way when it bakes a golden
//! template. Going through the package manager means the container's own
//! unattended-upgrades keeps the shipper patched — which is the entire reason
//! for leaving promtail, so installing the replacement in a way that needs a
//! human to update it would defeat the move.
//!
//! **Why one config for both kinds of container.** Alloy reads journald and
//! docker logs from the same file; a container with no docker simply matches
//! no files there, and a container with docker gets both. That removes the
//! split promtail forced — a sidecar for stacks that run containers and
//! nothing for the ones that do not.

/// Grafana's apt repository, and the key that signs it.
///
/// Pinned by URL rather than by version: apt is the thing keeping this
/// patched, so pinning a version here would put the update back in a human's
/// hands. The KEY is what makes that safe.
pub const APT_KEY_URL: &str = "https://apt.grafana.com/gpg.key";
pub const APT_LIST_LINE: &str =
    "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main";

/// Where the config lives, which is where the packaged unit already looks.
pub const CONFIG_PATH: &str = "/etc/alloy/config.alloy";

/// The labels every line carries, kept identical to what promtail set.
///
/// This is not cosmetic. Three Grafana dashboards group by `container_name`
/// and one filters on `job="docker"`; a shipper that delivers the same lines
/// under different labels would leave every one of them empty while looking
/// perfectly healthy from the container's side. F72 was exactly that fault
/// with one label, and it went unnoticed for months.
/// Turn the configured Loki address into the endpoint Alloy pushes to.
///
/// `loki_url` in `host.toml` is the BASE address — the coverage check queries
/// it — and pushing there gets a 404 from Loki with no clue what is wrong.
/// Measured 2026-09-02 on the first live deploy: Alloy started, reported
/// itself healthy, the deploy printed "Alloy shipping kyu → Loki", and every
/// batch was dropped with `status=404`. Zero lines arrived. Nothing but
/// querying Loki afterwards would have caught it, which is exactly why that
/// check is part of the migration and not an afterthought.
///
/// A URL that already names the push path is left alone, so an operator who
/// spells it out in full is not second-guessed.
pub fn push_url(loki_url: &str) -> String {
    let base = loki_url.trim_end_matches('/');
    if base.contains("/loki/api/") {
        return base.to_string();
    }
    format!("{}/loki/api/v1/push", base)
}

pub fn config(stack: &str, hostname: &str, loki_url: &str) -> String {
    format!(
        r#"// GENERATED by the homelab orchestrator. Edit the stack, not this file.
//
// Replaces promtail, which reached end of life on 2026-03-02. The labels
// below are deliberately identical to the ones promtail set, because the
// dashboards group by them.

logging {{
  level  = "warn"
  format = "logfmt"
}}

loki.write "default" {{
  endpoint {{
    url = "{loki}"
  }}
}}

// ── Docker container logs ────────────────────────────────────────────────
// Matches nothing on a container without docker, which is how the native
// stacks share this file instead of needing one of their own.
local.file_match "docker" {{
  path_targets = [{{
    __path__ = "/var/lib/docker/containers/*/*-json.log",
    job      = "docker",
    stack    = "{stack}",
    host     = "{host}",
  }}]
  sync_period = "30s"
}}

loki.source.file "docker" {{
  targets    = local.file_match.docker.targets
  forward_to = [loki.process.docker.receiver]
}}

loki.process "docker" {{
  // Docker wraps each line: the message is in `log`, and the container's
  // name is under `attrs.tag`. Reading `attrs.name` instead is what left
  // three dashboards empty for months (F72).
  stage.json {{
    expressions = {{ output = "log", stream = "stream", attrs = "attrs" }}
  }}
  stage.json {{
    expressions = {{ container_name = "tag" }}
    source      = "attrs"
  }}
  stage.labels {{
    values = {{ stream = "", container_name = "" }}
  }}
  stage.output {{
    source = "output"
  }}
  forward_to = [loki.write.default.receiver]
}}

// ── systemd journal ──────────────────────────────────────────────────────
// The half promtail never had here. On the native containers this IS the
// log: kyu, kyu-runner, http-switchboard and almanac all write to journald
// and nothing was reading it (F245).
loki.source.journal "journal" {{
  forward_to = [loki.write.default.receiver]
  labels     = {{
    job   = "systemd-journal",
    stack = "{stack}",
    host  = "{host}",
  }}
  relabel_rules = loki.relabel.journal.rules
}}

loki.relabel "journal" {{
  forward_to = []
  rule {{
    source_labels = ["__journal__systemd_unit"]
    target_label  = "unit"
  }}
}}

// ── The system log file, as promtail read it ─────────────────────────────
local.file_match "syslog" {{
  path_targets = [{{
    __path__ = "/var/log/syslog",
    job      = "syslog",
    stack    = "{stack}",
    host     = "{host}",
  }}]
  sync_period = "30s"
}}

loki.source.file "syslog" {{
  targets    = local.file_match.syslog.targets
  forward_to = [loki.write.default.receiver]
}}
"#,
        loki = push_url(loki_url),
        stack = stack,
        host = hostname
    )
}

/// The shell that installs Alloy on a container that does not have it.
///
/// Idempotent by design: it is run by every deploy, and a deploy that
/// reinstalled a package every time would be a deploy nobody dares repeat.
pub fn install_script() -> String {
    format!(
        "set -e; \
         if command -v alloy >/dev/null 2>&1; then echo already-installed; exit 0; fi; \
         export DEBIAN_FRONTEND=noninteractive; \
         mkdir -p /etc/apt/keyrings; \
         apt-get install -y -qq gpg curl >/dev/null; \
         curl -fsSL {key} | gpg --dearmor -o /etc/apt/keyrings/grafana.gpg; \
         echo '{list}' > /etc/apt/sources.list.d/grafana.list; \
         apt-get update -qq; \
         apt-get install -y -qq alloy; \
         echo installed",
        key = APT_KEY_URL,
        list = APT_LIST_LINE
    )
}

/// Alloy runs as its own user and must be allowed to read what it ships.
///
/// `adm` covers `/var/log/syslog`, `systemd-journal` covers journald, and
/// `docker` covers the container log directory — which only exists where
/// docker does, so the group add is allowed to fail there.
pub fn permissions_script() -> String {
    "usermod -aG adm,systemd-journal alloy 2>/dev/null || true; \
     getent group docker >/dev/null && usermod -aG docker alloy 2>/dev/null || true; \
     true"
        .to_string()
}

/// Alloy's own verdict on whether anything actually reached Loki.
///
/// The first live deploy of this step printed "Alloy shipping kyu → Loki"
/// while every batch was being dropped with a 404 and zero lines arrived.
/// "The service started" is not "the logs are shipping", and this project has
/// spent a whole day finding mechanisms that report success and are wired to
/// nothing. So the step asks Alloy afterwards.
///
/// Reads its Prometheus endpoint, which the package exposes on localhost.
pub const METRICS_URL: &str = "http://127.0.0.1:12345/metrics";

/// What the numbers mean, kept pure so the shell stays dumb.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Delivery {
    /// Bytes reached Loki and none were dropped since the restart.
    Shipping { sent: u64 },
    /// Alloy is dropping what it reads — the far end refused it.
    Dropping { dropped: u64 },
    /// Nothing sent and nothing dropped. On a busy container that is wrong;
    /// on a quiet one it is simply too early to tell, so it says so rather
    /// than picking one.
    Quiet,
    /// The question could not be asked.
    Unknown(String),
}

/// Parse `loki_write_sent_bytes_total` and `loki_write_dropped_bytes_total`
/// out of Alloy's metrics text.
pub fn delivery(metrics: &str) -> Delivery {
    if metrics.trim().is_empty() {
        return Delivery::Unknown("no answer from Alloy's metrics endpoint".into());
    }
    let sum = |needle: &str| -> u64 {
        metrics
            .lines()
            .filter(|l| l.starts_with(needle))
            .filter_map(|l| l.rsplit_once(' '))
            .filter_map(|(_, v)| v.trim().parse::<f64>().ok())
            .map(|v| v as u64)
            .sum()
    };
    let sent = sum("loki_write_sent_bytes_total");
    let dropped = sum("loki_write_dropped_bytes_total");
    if dropped > 0 {
        return Delivery::Dropping { dropped };
    }
    if sent > 0 {
        return Delivery::Shipping { sent };
    }
    Delivery::Quiet
}
