//! T49: the watch list follows the fleet instead of being maintained beside
//! it.
//!
//! The 36 monitors on Uptime Kuma were seeded once by a script and have
//! drifted ever since — on 2026-09-01 one was reporting Uptime Kuma itself
//! as down because it still named the address that service left that morning
//! (F157), and another carried the name of a stack that no longer exists
//! (F158). A new stack, meanwhile, arrives unwatched until somebody
//! remembers.
//!
//! The split is deliberate. The MECHANICAL half — one reachability monitor
//! per managed container — is exactly what goes stale when a stack is added,
//! renamed or destroyed, and that half is generated here. The APPLICATION
//! half stays in the seeder's own list, because `/health` versus `/ping`
//! versus `/up` is real knowledge about a service that no manifest holds:
//! kp-soft's `/up` answers only when Laravel reached its database, and the
//! switchboard's `?strict=1` answers 503 when it cannot do its job. Deriving
//! those from a template would replace knowledge with a guess.

/// One reachability monitor: what it is called and what it pings.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Monitor {
    pub name: String,
    pub host: String,
}

/// A stack's address without its CIDR suffix, or None when it has none.
fn ip_only(ip: &str) -> Option<&str> {
    let bare = ip.split('/').next()?.trim();
    (!bare.is_empty()).then_some(bare)
}

/// One monitor per stack, named the way the existing set is named so a
/// re-run recognises its own work and adds nothing twice.
///
/// Input is `(stack, ip)` pairs — everything host state already holds.
/// Sorted by name, so two runs over the same fleet produce the same list and
/// a diff means the fleet changed rather than the order did.
pub fn host_monitors(stacks: &[(String, String)]) -> Vec<Monitor> {
    let mut out: Vec<Monitor> = stacks
        .iter()
        .filter_map(|(stack, ip)| {
            ip_only(ip).map(|host| Monitor {
                name: format!("host · {}", stack),
                host: host.to_string(),
            })
        })
        .collect();
    out.sort_by(|a, b| a.name.cmp(&b.name));
    out.dedup_by(|a, b| a.name == b.name);
    out
}

/// The monitors that exist and should not: named `host · <stack>` for a
/// stack the fleet no longer has.
///
/// Returned rather than deleted. Removing somebody's monitor is the
/// irreversible direction and a deploy runs when nobody is watching — the
/// same reasoning as the orphan FILES a deploy reports and never removes
/// (Kenny, form H2b).
pub fn stale_monitors(existing: &[String], stacks: &[(String, String)]) -> Vec<String> {
    // F175, second site. An empty fleet list is almost never "the fleet has
    // no containers" — it is "the fleet could not be read". Judging against
    // it declares every host monitor stale, which is what the Python seeder
    // did on its first live run: eleven warnings about stacks that all
    // exist, because the generated file had not been written yet.
    //
    // A genuinely empty fleet would make every host monitor stale too, and
    // that answer would be correct — but it is so much rarer than the
    // failure that refusing to judge is the better trade. Nothing is lost by
    // waiting for a reading: this function only ever reports.
    if stacks.is_empty() {
        return Vec::new();
    }
    existing
        .iter()
        .filter(|name| name.starts_with("host · "))
        .filter(|name| {
            let stack = name.trim_start_matches("host · ");
            !stacks.iter().any(|(s, _)| s == stack)
        })
        .cloned()
        .collect()
}

/// Render the generated half as the file the seeder reads.
///
/// JSON, not YAML: the reader is a Python script and `json` is in its
/// standard library, so the seeder needs no parser dependency for the one
/// file it cannot run without.
///
/// The header names the generator on purpose. This file lands next to a
/// hand-written script in the same directory, and the next person to open it
/// has to be able to tell in one line which of the two to edit.
pub fn monitors_json(monitors: &[Monitor]) -> String {
    let mut s = String::from(
        "{\n  \"_comment\": \"GENERATED by the homelab orchestrator (T49) at \
         deploy time from the fleet manifests. Edit the fleet, not this file — \
         a deploy overwrites it. The APPLICATION monitors live in seed.py, \
         which is hand-written on purpose.\",\n  \"host_monitors\": [\n",
    );
    for (i, m) in monitors.iter().enumerate() {
        s.push_str(&format!(
            "    {{ \"name\": {}, \"hostname\": {} }}{}\n",
            json_str(&m.name),
            json_str(&m.host),
            if i + 1 == monitors.len() { "" } else { "," }
        ));
    }
    s.push_str("  ]\n}\n");
    s
}

/// Minimal JSON string escaping. The inputs are stack names and IP
/// addresses, but a stack name is operator-typed and a raw quote or
/// backslash in one would produce a file the seeder cannot parse — and it
/// would fail at 05:00 on the container, not here.
fn json_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}
