//! Build a DeploySpec from a local stack directory (shared by CLI and TUI).

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use serde::Deserialize;

use homelab_proto::{DeploySpec, FileBlob, GatewayRoute, StackManifest};

#[derive(Deserialize)]
struct StackFile {
    #[serde(flatten)]
    manifest: StackManifest,
    #[serde(default)]
    gateway_route: Option<GatewayRouteFile>,
}

#[derive(Deserialize)]
struct GatewayRouteFile {
    filename: String,
    #[serde(default = "default_gw")]
    gateway_vmid: u16,
}

fn default_gw() -> u16 {
    104
}

pub fn build_spec(dir: &Path) -> Result<DeploySpec, String> {
    let manifest_path = dir.join("lxc-compose.yml");
    let raw = std::fs::read_to_string(&manifest_path)
        .map_err(|e| format!("cannot read {}: {}", manifest_path.display(), e))?;
    let stack_file: StackFile =
        serde_yaml::from_str(&raw).map_err(|e| format!("manifest parse: {}", e))?;

    let mut files: Vec<FileBlob> = Vec::new();
    let mut env: BTreeMap<String, String> = BTreeMap::new();
    collect(dir, dir, &mut files, &mut env)?;

    let gateway_route = match stack_file.gateway_route.as_ref() {
        Some(g) => {
            let route_path = dir.join("traefik-routes.yml");
            let content = std::fs::read_to_string(&route_path)
                .map_err(|e| format!("gateway_route set but {}: {}", route_path.display(), e))?;
            Some(GatewayRoute {
                gateway_vmid: g.gateway_vmid,
                filename: g.filename.clone(),
                content,
            })
        }
        None => None,
    };

    Ok(DeploySpec {
        manifest: stack_file.manifest,
        files,
        env,
        gateway_route,
    })
}

fn collect(
    root: &Path,
    dir: &Path,
    files: &mut Vec<FileBlob>,
    env: &mut BTreeMap<String, String>,
) -> Result<(), String> {
    let entries = match std::fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return Ok(()),
    };
    for entry in entries.flatten() {
        let path: PathBuf = entry.path();
        let name = entry.file_name().to_string_lossy().to_string();
        if path.is_dir() {
            collect(root, &path, files, env)?;
            continue;
        }
        let rel = path
            .strip_prefix(root)
            .unwrap()
            .to_string_lossy()
            .to_string();
        if rel == "lxc-compose.yml" || rel == "traefik-routes.yml" {
            continue;
        }
        let content = std::fs::read_to_string(&path)
            .map_err(|_| format!("non-utf8 file not supported: {}", rel))?;
        if name == ".env" {
            let app = path
                .parent()
                .and_then(|p| p.file_name())
                .map(|s| s.to_string_lossy().to_string())
                .unwrap_or_default();
            env.insert(app, content);
        } else {
            files.push(FileBlob {
                path: rel,
                content,
                mode: None,
            });
        }
    }
    Ok(())
}

/// Scan a directory for deployable stack dirs (those with lxc-compose.yml).
pub fn scan_local_stacks(base: &Path) -> Vec<(String, PathBuf)> {
    let mut out = Vec::new();
    if let Ok(entries) = std::fs::read_dir(base) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() && path.join("lxc-compose.yml").exists() {
                out.push((entry.file_name().to_string_lossy().to_string(), path));
            }
        }
    }
    out.sort();
    out
}

/// E7: generate the disaster-recovery runbook from the local stacks dir.
/// Deliberately plain markdown with copy-pasteable commands — this document
/// must be useful when the TUI, the host daemon, or the whole host is down.
/// Returns the number of stacks included.
pub fn generate_runbook(stacks_dir: &Path, out_path: &str) -> Result<usize, String> {
    let stacks = scan_local_stacks(stacks_dir);
    let mut doc = String::new();
    doc.push_str(
        "# Disaster-recovery runbook\n\n\
         *Generated by `homelab runbook` — regenerate after every stack change.*\n\n\
         This document assumes the worst: the TUI is gone, the host daemon is\n\
         down, maybe the whole Proxmox host is fresh. Everything below is plain\n\
         shell on the Proxmox host (root) unless stated otherwise.\n\n\
         ## Layer 0 — What runs where\n\n\
         - Proxmox host `10.10.5.250` (ssh root, key auth).\n\
         - The 12TB and 18TB data disks are attached to the **Proxmox host**\n\
           (`/HDD12TB`, `/HDD18TB`) and bind-mounted into CT 103\n\
           (infra-fileserver), which shares them over Samba; CT 105/106 also\n\
           bind-mount the 18TB subvolume. Losing a container never loses this\n\
           data; losing the host means re-attaching these disks first.\n\
         - App config data lives on the host under `/appdata/<stack>/…`,\n\
           bind-mounted into each container — it survives container recreation\n\
           and is what restic backs up.\n\
         - Host daemon: `homelab-host.service`, config `/etc/homelab/host.toml`\n\
           (token), state + git intent repo + incidents under `/var/lib/homelab`.\n\n\
         ## Layer 1 — Recover the host daemon\n\n\
         ```sh\n\
         systemctl status homelab-host       # is it running?\n\
         journalctl -u homelab-host -n 50    # why not?\n\
         curl -sk https://127.0.0.1:8443/api/health\n\
         ```\n\
         Reinstall if needed: build `homelab-host` (Debian 12 target), copy to\n\
         `/usr/local/bin/homelab-host`, keep the existing `/etc/homelab/host.toml`\n\
         and systemd unit, `systemctl daemon-reload && systemctl restart homelab-host`.\n\
         The TLS cert lives in `/var/lib/homelab` — keep it to keep the client pin.\n\n\
         ## Layer 2 — Recover a stack without the daemon\n\n\
         Every stack is just an LXC + docker compose files. By hand:\n\
         ```sh\n\
         pct list                              # what exists\n\
         pct start <vmid>\n\
         pct exec <vmid> -- sh -c 'cd /opt/<stack>/<app> && docker compose up -d'\n\
         ```\n\
         The exact files the daemon deployed are in git: `/var/lib/homelab/repo`.\n\n\
         ## Layer 3 — Restore data from backup\n\n\
         Restic repos per stack: `rclone:gdrive:homelab-backups/<stack>-config`, password\n\
         file `/var/lib/homelab/secrets/restic.pw` (keep an offline copy of this\n\
         password — without it backups are unreadable!).\n\
         ```sh\n\
         export RESTIC_REPOSITORY=rclone:gdrive:homelab-backups/<stack>-config\n\
         export RESTIC_PASSWORD_FILE=/var/lib/homelab/secrets/restic.pw\n\
         restic snapshots\n\
         restic restore latest --target /\n\
         ```\n\n\
         ## Stacks\n\n",
    );
    let mut included = 0usize;
    for (name, path) in &stacks {
        let raw = std::fs::read_to_string(path.join("lxc-compose.yml"))
            .map_err(|e| format!("{}: {}", name, e))?;
        // Legacy v1 stacks in the same dir don't parse as v2 manifests —
        // list them as such rather than aborting the whole runbook.
        let m: homelab_core::manifest::StackManifest = match serde_yaml::from_str(&raw) {
            Ok(m) => m,
            Err(_) => {
                doc.push_str(&format!(
                    "### {} — LEGACY (v1 manifest, not deployable by v2)\n\n\
                     Recover by hand per Layer 2, or migrate it to a v2 stack first.\n\n",
                    name
                ));
                continue;
            }
        };
        included += 1;
        doc.push_str(&format!(
            "### {} (vmid {})\n\n\
             - hostname `{}`, ip `{}`\n\
             - resources: {} core(s), {} MiB RAM, {} MiB swap, {} GiB disk\n\
             - apps: {}\n\
             - recreate from scratch: `homelab deploy stacks/{}` (or by hand per Layer 2)\n\
             - data restore: restic repo `…:{}-config`, then redeploy\n\n",
            m.stack_name,
            m.vmid,
            m.hostname,
            m.network.ip,
            m.resources.cores,
            m.resources.memory_mb,
            m.resources.swap_mb,
            m.resources.disk_gb,
            m.apps.join(", "),
            name,
            m.stack_name,
        ));
    }
    doc.push_str(
        "## Full-host rebuild order\n\n\
         1. Install Proxmox, restore network config (vmbr0, VLAN 10).\n\
         2. Re-attach `/HDD12TB` + `/HDD18TB` mounts.\n\
         3. Restore `/etc/homelab/host.toml` + `/var/lib/homelab` (or accept a\n\
            new TLS cert + re-pin the client, and a fresh token).\n\
         4. Recreate no-touch guests from Proxmox backups (HA VM 101 first).\n\
         5. `homelab deploy` each stack above; restic restore fills the data.\n",
    );
    std::fs::write(out_path, &doc).map_err(|e| e.to_string())?;
    Ok(included)
}
