//! fix-144 (expert panel 2026-09-27, update-policy-doc-drift): the update
//! policy of every app and native service, generated from the stack files
//! into a marked section of docs/deployment/UPDATE_POLICY.md.
//!
//! The document kept its lists by hand and they disagreed with the stack
//! files and with each other: http-switchboard under "the docker path", kyu
//! "publishes no release assets at all", almanac "updates itself" and
//! `manual` in one breath (REGISTER F192: "classes and the fleet disagree in
//! seven places"). A list a human must keep in step drifts; this one is
//! written by `homelab update-policy`, and a test fails when the committed
//! copy is stale, as for the DR runbook.

use std::path::Path;

use homelab_core::native::UpdatePolicy;
use serde_yaml::Value;

pub const BEGIN: &str = "<!-- BEGIN generated by `homelab update-policy` -->";
pub const END: &str = "<!-- END generated -->";

const LABEL: &str = "com.homelab.update.policy";

fn sorted_dirs(dir: &Path) -> Vec<std::path::PathBuf> {
    let mut v: Vec<_> = std::fs::read_dir(dir)
        .map(|rd| {
            rd.flatten()
                .map(|e| e.path())
                .filter(|p| p.is_dir())
                .collect()
        })
        .unwrap_or_default();
    v.sort();
    v
}

fn name(p: &Path) -> String {
    p.file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_default()
}

/// A service's policy label, from either compose form (`- key=value` or
/// `key: value`); None when it carries none.
fn policy_label(svc: &Value) -> Option<String> {
    match svc.get("labels")? {
        Value::Sequence(items) => items.iter().filter_map(Value::as_str).find_map(|l| {
            l.strip_prefix(LABEL)
                .and_then(|r| r.strip_prefix('='))
                .map(|v| v.trim().to_string())
        }),
        Value::Mapping(m) => m.get(LABEL).and_then(|v| match v {
            Value::String(s) => Some(s.clone()),
            other => serde_yaml::to_string(other)
                .ok()
                .map(|s| s.trim().to_string()),
        }),
        _ => None,
    }
}

/// `name:tag@sha256:<12 hex>…`: the digest decides what runs, and twelve
/// characters are enough to tell two apart in a table.
fn short_image(image: &str) -> String {
    match image.split_once("@sha256:") {
        Some((name, digest)) if digest.len() > 12 => format!("{}@sha256:{}…", name, &digest[..12]),
        _ => image.to_string(),
    }
}

fn policy_name(p: &UpdatePolicy) -> &'static str {
    match p {
        UpdatePolicy::Manual => "manual",
        UpdatePolicy::Auto => "auto",
        UpdatePolicy::OwnVerb => "self",
    }
}

/// The generated section: one row per compose service, one per native unit.
pub fn policy_table(stacks_dir: &Path) -> Result<String, String> {
    let mut compose = Vec::new();
    let mut natives = Vec::new();
    for stack_dir in sorted_dirs(stacks_dir) {
        let stack = name(&stack_dir);
        for app_dir in sorted_dirs(&stack_dir) {
            let file = app_dir.join("docker-compose.yml");
            let Ok(raw) = std::fs::read_to_string(&file) else {
                continue;
            };
            let mut doc: Value =
                serde_yaml::from_str(&raw).map_err(|e| format!("{}: {}", file.display(), e))?;
            // The registry caches share one `<<: *cache` anchor; the label and
            // the image live there.
            doc.apply_merge()
                .map_err(|e| format!("{}: {}", file.display(), e))?;
            let Some(services) = doc.get("services").and_then(Value::as_mapping) else {
                continue;
            };
            let rows: Vec<(String, Option<String>, String)> = services
                .iter()
                .map(|(k, svc)| {
                    (
                        k.as_str().unwrap_or("?").to_string(),
                        policy_label(svc),
                        svc.get("image")
                            .and_then(Value::as_str)
                            .unwrap_or("(built here)")
                            .to_string(),
                    )
                })
                .collect();
            let labels: std::collections::BTreeSet<&Option<String>> =
                rows.iter().map(|(_, l, _)| l).collect();
            let note = if labels.len() > 1 {
                "mixed: the update reads one label for the whole app, the first container's"
            } else {
                ""
            };
            for (svc, label, image) in rows {
                compose.push(format!(
                    "| {} | {} | {} | {} | `{}` | {} |",
                    stack,
                    name(&app_dir),
                    svc,
                    label
                        .map(|l| format!("`{}`", l))
                        .unwrap_or_else(|| "none".into()),
                    short_image(&image),
                    note
                ));
            }
        }
        for (unit, m) in crate::spec::native_manifests_for(&stack_dir) {
            let n = m.nightly_updates();
            let release = n.release && m.release_repo.is_some();
            let own = n.own_cmd && m.update_cmd.is_some();
            let does = match (release, own) {
                (true, true) => "installs a newer release, then runs its own update verb",
                (true, false) => "installs a newer release",
                (false, true) => "runs its own update verb",
                (false, false) => "nothing; updated on request",
            };
            natives.push(format!(
                "| {} | {} | `{}` | {} | {} |",
                stack,
                unit,
                policy_name(&m.update_policy),
                does,
                m.release_repo
                    .as_deref()
                    .map(|r| format!("`{}`", r))
                    .unwrap_or_else(|| "none".into())
            ));
        }
    }
    let mut out = String::new();
    out.push_str(
        "*Generated from the stack files by `homelab update-policy`; do not edit by hand. \
         A test fails when this copy is stale.*\n\n",
    );
    out.push_str("### Compose apps (`com.homelab.update.policy`)\n\n");
    out.push_str("| Stack | App | Service | Policy | Image | Note |\n|---|---|---|---|---|---|\n");
    for r in &compose {
        out.push_str(r);
        out.push('\n');
    }
    out.push_str("\n### Native services (`update_policy` in `service.yml`)\n\n");
    out.push_str(
        "| Stack | Unit | Policy | The nightly round | Release |\n|---|---|---|---|---|\n",
    );
    for r in &natives {
        out.push_str(r);
        out.push('\n');
    }
    Ok(out)
}

/// `doc` with the section between the markers replaced by `table`. A
/// document without both markers is refused, never appended to.
pub fn splice(doc: &str, table: &str) -> Result<String, String> {
    let start = doc
        .find(BEGIN)
        .ok_or_else(|| format!("no `{}` marker", BEGIN))?;
    let body = start + BEGIN.len();
    let end = doc[body..]
        .find(END)
        .map(|i| body + i)
        .ok_or_else(|| format!("no `{}` marker after the first", END))?;
    Ok(format!("{}\n{}{}", &doc[..body], table, &doc[end..]))
}

/// Regenerate the section in `doc_path`; returns how many rows it holds.
pub fn write_update_policy(stacks_dir: &Path, doc_path: &Path) -> Result<usize, String> {
    let doc =
        std::fs::read_to_string(doc_path).map_err(|e| format!("{}: {}", doc_path.display(), e))?;
    let table = policy_table(stacks_dir)?;
    let rows = table
        .lines()
        .filter(|l| l.starts_with("| ") && !l.starts_with("| Stack"))
        .count();
    let out = splice(&doc, &table)?;
    if out != doc {
        std::fs::write(doc_path, out).map_err(|e| format!("{}: {}", doc_path.display(), e))?;
    }
    Ok(rows)
}
