server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions/positions.yaml

clients:
  - url: http://10.10.10.4:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets: [localhost]
        labels:
          job: docker
          stack: __STACK__
          host: __HOSTNAME__
          __path__: /var/lib/docker/containers/*/*-json.log
