"""Keep Uptime Kuma's monitor set in step with the fleet (T49).

Two halves, deliberately split (D87, D90):

  * The MECHANICAL half — one reachability monitor per managed container —
    is GENERATED by the orchestrator into HOST_MONITORS_FILE at deploy time,
    the same way it renders Prometheus targets and the Grafana dashboard.
    That half is exactly what goes stale when a stack is added, renamed or
    destroyed. On 2026-09-01 one monitor had been reporting Uptime Kuma
    itself as down for eight hours because it still named the address the
    service left that morning (F157), and another carried the name of a
    stack that no longer exists (F158).

  * The APPLICATION half is the list below, hand-written and staying that
    way. Whether a service answers on /health, /ping, /up or /api/v1/status
    is real knowledge that no manifest holds: kp-soft's /up answers only
    when Laravel reached its database and its cache, and the switchboard's
    ?strict=1 answers 503 when it cannot do its job. Deriving those from a
    template would replace knowledge with a guess, and a monitor that is red
    from birth teaches its reader to ignore the whole board.

Idempotent: a monitor whose name already exists is left exactly as it is,
including Kenny's own edits to it. Nothing here ever deletes a monitor —
stale ones are reported and left alone, the same rule the deploy follows for
orphaned files (Kenny, form H2b). Removing somebody's monitor is the
irreversible direction, and this runs when nobody is watching.
"""

import json
import os
import sys
import time

from uptime_kuma_api import UptimeKumaApi, MonitorType

OK = ["200-299"]
OK_REDIRECT = ["200-299", "302"]
OK_TRAEFIK = ["404"]  # the correct answer for a host header it does not route

# Every endpoint below was probed and answered before it was written down.
APPLICATION_MONITORS = [
    # (name, url, accepted status codes)
    ("gateway · traefik", "http://10.10.10.4:80/", OK_TRAEFIK),
    ("gateway · grafana", "http://10.10.10.4:3000/api/health", OK),
    ("gateway · loki", "http://10.10.10.4:3100/ready", OK),
    ("uptime · web", "http://10.10.10.7:3001/", OK_REDIRECT),
    ("metrics · prometheus", "http://10.10.10.13:9090/-/healthy", OK),
    ("metrics · alertmanager", "http://10.10.10.13:9093/-/healthy", OK),
    ("media · jellyfin", "http://10.10.10.6:8096/health", OK),
    ("media · seerr", "http://10.10.10.6:5055/api/v1/status", OK),
    ("media · sonarr", "http://10.10.10.6:8989/ping", OK),
    ("media · radarr", "http://10.10.10.6:7878/ping", OK),
    ("media · prowlarr", "http://10.10.10.6:9696/ping", OK),
    ("media · bazarr", "http://10.10.10.6:6767/", OK),
    ("downloader · qbittorrent", "http://10.10.10.5:8080/", OK),
    ("syncthing · web", "http://10.10.10.8:8384/rest/noauth/health", OK),
    ("almanac · healthz", "http://10.10.10.12:8080/healthz", OK),
    ("kyu · runner", "http://10.10.10.9:8082/healthz", OK),
    # The STRICT health deliberately: it answers 503 when the switchboard
    # cannot do its job, which is what a monitor should see. Container and
    # unit health stay on plain /healthz — wiring a restart to the strict one
    # would restart this service because Home Assistant is down.
    ("kyu · switchboard", "http://10.10.10.9:8083/healthz?strict=1", OK),
    ("paperwork · actual", "http://10.10.10.14:5006/", OK),
    ("paperwork · stirling", "http://10.10.10.14:8080/login", OK),
    ("paperwork · paperless", "http://10.10.10.14:8000/accounts/login/", OK),
    ("home · homepage", "http://10.10.10.15:3000/", OK),
    ("kp-soft · site", "http://10.10.10.16:8080/up", OK),
    # Through cloudflared and Traefik. Every *.kp-soft.dev name sits behind
    # Cloudflare Access, so a healthy answer is the 302 to its login page.
    # The edge is one wildcard route, so a single external check already sees
    # the tunnel fail; two guard against a fluke in one of them.
    ("extern · fin.kp-soft.dev", "https://fin.kp-soft.dev/", OK_REDIRECT),
    ("extern · docs.kp-soft.dev", "https://docs.kp-soft.dev/", OK_REDIRECT),
]


def env(name, default=None):
    v = os.environ.get(name, default)
    if v is None or v == "":
        print(f"[seed] FATAL: {name} is not set", flush=True)
        sys.exit(1)
    return v


def load_host_monitors(path):
    """The generated half. A missing or broken file is reported and skipped,
    never guessed around: seeding the application half is still worth doing,
    and inventing host monitors would create ones that are red forever."""
    try:
        with open(path, "r", encoding="utf-8") as fh:
            data = json.load(fh)
    except FileNotFoundError:
        print(f"[seed] WARN: {path} does not exist — the orchestrator has "
              "not written the host monitors yet; skipping that half",
              flush=True)
        return []
    except (OSError, ValueError) as e:
        print(f"[seed] WARN: {path} is unreadable ({e}) — skipping the host "
              "monitors rather than guessing them", flush=True)
        return []
    out = []
    for entry in data.get("host_monitors", []):
        name, hostname = entry.get("name"), entry.get("hostname")
        if name and hostname:
            out.append((name, hostname))
    return out


def seed_once(api, host_monitors):
    have = {m["name"] for m in api.get_monitors()}
    added = skipped = 0

    for name, url, accepted in APPLICATION_MONITORS:
        if name in have:
            skipped += 1
            continue
        api.add_monitor(type=MonitorType.HTTP, name=name, url=url,
                        interval=60, maxretries=2,
                        accepted_statuscodes=accepted)
        added += 1
        print(f"[seed]   + {name}", flush=True)

    for name, hostname in host_monitors:
        if name in have:
            skipped += 1
            continue
        api.add_monitor(type=MonitorType.PING, name=name, hostname=hostname,
                        interval=60, maxretries=2)
        added += 1
        print(f"[seed]   + {name}", flush=True)

    # Reported, never deleted (H2b). A monitor named for a stack the fleet no
    # longer has is the F158 shape: it stays green forever, or red forever,
    # and either way it is furniture rather than information.
    fleet = {n for n, _ in host_monitors}
    stale = sorted(n for n in have
                   if n.startswith("host · ") and n not in fleet)
    for name in stale:
        print(f"[seed] WARN: '{name}' watches a stack the fleet does not "
              "have — remove it in Uptime Kuma if that is right", flush=True)

    print(f"[seed] {added} added, {skipped} already existed, "
          f"{len(stale)} stale", flush=True)


def main():
    url = env("KUMA_URL")
    user = env("KUMA_USER")
    password = env("KUMA_PASSWORD")
    monitors_file = env("HOST_MONITORS_FILE", "/config/host-monitors.json")
    interval = int(env("SEED_INTERVAL_SECONDS", "3600"))

    while True:
        try:
            api = UptimeKumaApi(url)
            try:
                api.login(user, password)
                seed_once(api, load_host_monitors(monitors_file))
            finally:
                api.disconnect()
        except Exception as e:  # noqa: BLE001 — a loop that dies stops watching
            # Uptime Kuma restarting, a network blip, a changed password: all
            # of them are worth one loud line and another try. Exiting here
            # would leave every future stack unwatched, and the container
            # would be counted as "not running" by the deploy verification.
            print(f"[seed] ERROR: {type(e).__name__}: {e}", flush=True)
        time.sleep(interval)


if __name__ == "__main__":
    main()
