"""Keep Uptime Kuma's monitor set in step with the fleet (T49).

Two halves, deliberately split (D87, D90):

  * The MECHANICAL half — one reachability monitor per managed container —
    is GENERATED by the orchestrator into HOST_MONITORS_FILE at deploy time,
    the same way it renders Prometheus targets and the Grafana dashboard.
    That half is exactly what goes stale when a stack is added, renamed or
    destroyed. On 2026-09-01 one monitor had been reporting Uptime Kuma
    itself as down for eight hours because it still named the address the
    service left that morning (F157), and another carried the name of a
    stack that no longer exists (F158).

  * The APPLICATION half is the list below, hand-written and staying that
    way. Whether a service answers on /health, /ping, /up or /api/v1/status
    is real knowledge that no manifest holds: kp-soft's /up answers only
    when Laravel reached its database and its cache, and the switchboard's
    ?strict=1 answers 503 when it cannot do its job. Deriving those from a
    template would replace knowledge with a guess, and a monitor that is red
    from birth teaches its reader to ignore the whole board.

Declarative (Kenny, 2026-09-27): Uptime Kuma holds exactly what this file and
the generated host list declare. A declared monitor is added once and then
only its address is kept equal to the file; a monitor nothing declares is
removed, a hand-made one included, since those belong in this file too. A
run that would remove more than a quarter of the monitors at once is refused
as a truncated list. This replaces the 2026-09-01 rule (H2b) that the seeder
never deletes a monitor.
"""

import json
import os
import sys
import time

try:
    from uptime_kuma_api import UptimeKumaApi, MonitorType, NotificationType
except ImportError:  # the planning functions are tested without the client
    UptimeKumaApi = MonitorType = NotificationType = None

# Kenny, 2026-09-27: the watch list is declarative, all of it. Every monitor
# Uptime Kuma holds is declared here or in the generated host list; one that
# is not is removed, and one whose address changed is corrected. A monitor
# made by hand belongs in APPLICATION_MONITORS like any other. This replaces
# the 2026-09-01 rule (H2b) that the seeder never deletes a monitor. Every
# monitor it manages carries this tag, so the Kuma UI shows which ones are
# file-driven (all of them, from now on).
OWNER_TAG = "homelab-seeder"
# A desired list that suddenly lost more than this share of the owned
# monitors is treated as truncated (a half-written file, a bug), not as a
# fleet that shrank: nothing is removed and the run says why.
DELETE_CAP_FRACTION = 0.25

OK = ["200-299"]
OK_REDIRECT = ["200-299", "302"]
OK_TRAEFIK = ["404"]  # the correct answer for a host header it does not route

# Every endpoint below was probed and answered before it was written down.
APPLICATION_MONITORS = [
    # (name, url, accepted status codes)
    ("gateway · traefik", "http://10.10.10.4:80/", OK_TRAEFIK),
    ("uptime · web", "http://10.10.10.7:3001/", OK_REDIRECT),
    ("metrics · prometheus", "http://10.10.10.13:9090/-/healthy", OK),
    ("metrics · alertmanager", "http://10.10.10.13:9093/-/healthy", OK),
    # Moved from the gateway with the services (fix-90, 2026-09-27); the
    # names follow the stack, so Kuma starts these two with a fresh history.
    ("metrics · grafana", "http://10.10.10.13:3000/api/health", OK),
    ("metrics · loki", "http://10.10.10.13:3100/ready", OK),
    ("media · jellyfin", "http://10.10.10.6:8096/health", OK),
    ("media · seerr", "http://10.10.10.6:5055/api/v1/status", OK),
    ("media · sonarr", "http://10.10.10.6:8989/ping", OK),
    ("media · radarr", "http://10.10.10.6:7878/ping", OK),
    ("media · prowlarr", "http://10.10.10.6:9696/ping", OK),
    ("media · bazarr", "http://10.10.10.6:6767/", OK),
    ("downloader · qbittorrent", "http://10.10.10.5:8080/", OK),
    ("syncthing · web", "http://10.10.10.8:8384/rest/noauth/health", OK),
    ("almanac · healthz", "http://10.10.10.12:8080/healthz", OK),
    # The hub itself. Made by hand in Uptime Kuma before the seeder existed;
    # declared here on 2026-09-27 under the same name, so its history stays
    # (Kenny: even a hand-made monitor is declared in a file).
    ("kyu", "http://10.10.10.9:8080/healthz", OK),
    ("kyu · runner", "http://10.10.10.9:8082/healthz", OK),
    # The STRICT health deliberately: it answers 503 when the switchboard
    # cannot do its job, which is what a monitor should see. Container and
    # unit health stay on plain /healthz — wiring a restart to the strict one
    # would restart this service because Home Assistant is down.
    ("kyu · switchboard", "http://10.10.10.9:8083/healthz?strict=1", OK),
    ("paperwork · actual", "http://10.10.10.14:5006/", OK),
    ("paperwork · stirling", "http://10.10.10.14:8080/login", OK),
    ("paperwork · paperless", "http://10.10.10.14:8000/accounts/login/", OK),
    ("home · homepage", "http://10.10.10.15:3000/", OK),
    # Declared 2026-09-27 (expert panel, kuma-coverage-and-seeder-drift):
    # sp.kp-soft.dev bypasses Access, and every docker pull in the fleet goes
    # through the cache, yet neither had a monitor. Both probed from CT 107
    # before they were written down: 200 each.
    ("productivity · supersync", "http://10.10.10.11:1900/health", OK),
    ("registry · docker.io cache", "http://10.10.10.17:5000/v2/", OK),
    ("kp-soft · site", "http://10.10.10.16:8080/up", OK),
    # Through cloudflared and Traefik. Every *.kp-soft.dev name sits behind
    # Cloudflare Access, so a healthy answer is the 302 to its login page.
    # The edge is one wildcard route, so a single external check already sees
    # the tunnel fail; two guard against a fluke in one of them.
    ("extern · fin.kp-soft.dev", "https://fin.kp-soft.dev/", OK_REDIRECT),
    ("extern · docs.kp-soft.dev", "https://docs.kp-soft.dev/", OK_REDIRECT),
]


# Uptime Kuma as a source for almanac (homelab ask-6): every state change of
# a monitor becomes a 15-minute, not-busy event on the Infra calendar. Kuma
# renders this Liquid template itself, so it speaks almanac's own event shape
# and needs no HTTPSwitchboard in between. Rendered and parsed against
# liquidjs 10 before it was written down; the `json` filter is what keeps a
# quote in a monitor's error message from breaking the body.
#
# One event per state change, not one per incident: the recovery cannot know
# when the outage started. The external_id is the monitor plus the heartbeat
# second, so Kuma resending the same heartbeat updates the event rather than
# adding a second one. Kuma's own "Test" button sends no heartbeat and is
# answered 422 by almanac; that is the expected reply to a test.
ALMANAC_NOTIFICATION = "almanac · infra calendar"
ALMANAC_BODY = (
    '{% assign at = heartbeatJSON.time | replace: " ", "T" | truncate: 19, "" %}'
    '{% if heartbeatJSON.status == 0 %}'
    '{% assign what = "down" %}{% assign color = "tomato" %}'
    '{% else %}'
    '{% assign what = "back up" %}{% assign color = "sage" %}'
    '{% endif %}'
    '{% capture title %}{{ monitorJSON.name }} {{ what }}{% endcapture %}'
    '{"title": {{ title | json }}, "start": "{{ at }}Z", "timezone": "UTC", '
    '"duration_minutes": 15, "busy": false, "color": "{{ color }}", '
    '"description": {{ heartbeatJSON.msg | json }}, '
    '"external_id": "kuma-{{ monitorJSON.id }}-{{ at }}"}'
)


def env(name, default=None):
    v = os.environ.get(name, default)
    if v is None or v == "":
        print(f"[seed] FATAL: {name} is not set", flush=True)
        sys.exit(1)
    return v


def load_host_monitors(path):
    """Returns (monitors, had_a_list). The second value matters: an empty
    list because the file said so is a fleet with no containers; an empty
    list because the file is missing is no information at all."""
    """The generated half. A missing or broken file is reported and skipped,
    never guessed around: seeding the application half is still worth doing,
    and inventing host monitors would create ones that are red forever."""
    try:
        with open(path, "r", encoding="utf-8") as fh:
            data = json.load(fh)
    except FileNotFoundError:
        print(f"[seed] WARN: {path} does not exist — the orchestrator has "
              "not written the host monitors yet; skipping that half",
              flush=True)
        return [], False
    except (OSError, ValueError) as e:
        print(f"[seed] WARN: {path} is unreadable ({e}) — skipping the host "
              "monitors rather than guessing them", flush=True)
        return [], False
    out = []
    for entry in data.get("host_monitors", []):
        name, hostname = entry.get("name"), entry.get("hostname")
        if name and hostname:
            out.append((name, hostname))
    return out, True


def ensure_almanac_notification(api):
    """Returns (notification id or None, what happened).

    Created once, then left alone like every monitor here: a notification
    whose name exists is never rewritten, so Kenny's own edits to it stand.
    Creating it attaches it to every existing monitor (applyExisting) — the
    one place this seeder touches a monitor it did not just add, and only by
    adding a notification to it, never by changing what it checks.

    Without ALMANAC_KUMA_TOKEN nothing is created: a webhook almanac answers
    401 is a notification that fails on every outage, which is worse than
    none. The token is issued for source `uptime-kuma` on almanac's
    dashboard and travels into .env through the vault like KUMA_PASSWORD.
    """
    for n in api.get_notifications():
        if n.get("name") == ALMANAC_NOTIFICATION:
            return n.get("id"), "exists"

    token = os.environ.get("ALMANAC_KUMA_TOKEN", "")
    if not token:
        print("[seed] INFO: ALMANAC_KUMA_TOKEN is not set, so outages are "
              "not sent to almanac", flush=True)
        return None, "no-token"

    base = env("ALMANAC_URL", "http://10.10.10.12:8080").rstrip("/")
    created = api.add_notification(
        name=ALMANAC_NOTIFICATION,
        type=NotificationType.WEBHOOK,
        isDefault=True,
        applyExisting=True,
        webhookURL=f"{base}/v1/ingest/uptime-kuma",
        webhookContentType="custom",
        webhookCustomBody=ALMANAC_BODY,
        webhookAdditionalHeaders=json.dumps(
            {"Authorization": f"Bearer {token}"}),
    )
    print(f"[seed]   + notification {ALMANAC_NOTIFICATION}", flush=True)
    return created.get("id"), "added"


# The dispatcher in Home Assistant (T64 kuma-channel, Kenny 2026-09-26).
# Until this existed Kuma watched forty monitors and told nobody: zero
# notifications in its database. It posts straight to HA, NOT through kyu,
# because one of the things Kuma has to report is kyu itself being down.
# HA's automation.uptime_kuma_webhook logs every change and pushes a monitor
# that went down; the URL carries the webhook id, which is a credential, so
# it comes from latch like KUMA_PASSWORD and never sits in this repository.
HA_NOTIFICATION = "home assistant · dispatcher"


def ensure_ha_notification(api):
    """Returns (notification id or None, what happened). Same contract as the
    almanac one below: created once, never rewritten, attached to every
    existing monitor on creation, and not created without its URL."""
    for n in api.get_notifications():
        if n.get("name") == HA_NOTIFICATION:
            return n.get("id"), "exists"

    url = os.environ.get("HA_KUMA_WEBHOOK_URL", "")
    if not url:
        print("[seed] INFO: HA_KUMA_WEBHOOK_URL is not set, so outages are "
              "not sent to Home Assistant", flush=True)
        return None, "no-url"

    created = api.add_notification(
        name=HA_NOTIFICATION,
        type=NotificationType.WEBHOOK,
        isDefault=True,
        applyExisting=True,
        webhookURL=url,
        webhookContentType="json",
    )
    print(f"[seed]   + notification {HA_NOTIFICATION}", flush=True)
    return created.get("id"), "added"


def is_owned(m):
    return any(t.get("name") == OWNER_TAG for t in (m.get("tags") or []))


def plan_owned(monitors, desired, judged):
    """What to tag, remove and correct, as a pure function (tested).

    `desired` maps a monitor name to its declared target (a URL for an HTTP
    monitor, a hostname for a ping). Returns (to_tag, to_delete, refused,
    to_fix): declared monitors that lack the tag; monitors no file declares;
    a reason when removal was refused; and (monitor, target) pairs whose
    address no longer matches the file (the F157 shape).
    """
    to_tag = [m for m in monitors if m["name"] in desired and not is_owned(m)]
    to_fix = []
    for m in monitors:
        want = desired.get(m["name"]) if isinstance(desired, dict) else None
        have = m.get("url") or m.get("hostname") or ""
        if want and have and want != have:
            to_fix.append((m, want))
    if not judged:
        return to_tag, [], "no generated host-monitor list, so nothing is judged", to_fix
    to_delete = [m for m in monitors if m["name"] not in desired]
    cap = max(3, int(len(monitors) * DELETE_CAP_FRACTION))
    if len(to_delete) > cap:
        return to_tag, [], (f"{len(to_delete)} monitors to remove is more than {cap}; "
                            "the desired list looks truncated, so nothing is removed"), to_fix
    return to_tag, to_delete, None, to_fix


def ensure_owner_tag(api):
    for t in api.get_tags():
        if t.get("name") == OWNER_TAG:
            return t["id"]
    return api.add_tag(name=OWNER_TAG, color="#2f6fed")["id"]


def seed_once(api, host_monitors, have_generated_list):
    have = {m["name"] for m in api.get_monitors()}
    added = skipped = 0

    # Kuma applies a default notification only in its own UI, so a monitor
    # added through the API has to name it.
    notification_id, almanac_state = ensure_almanac_notification(api)
    ha_id, ha_state = ensure_ha_notification(api)
    ids = [i for i in (notification_id, ha_id) if i]
    notify = {"notificationIDList": ids} if ids else {}

    for name, url, accepted in APPLICATION_MONITORS:
        if name in have:
            skipped += 1
            continue
        api.add_monitor(type=MonitorType.HTTP, name=name, url=url,
                        interval=60, maxretries=2,
                        accepted_statuscodes=accepted, **notify)
        added += 1
        print(f"[seed]   + {name}", flush=True)

    for name, hostname in host_monitors:
        if name in have:
            skipped += 1
            continue
        api.add_monitor(type=MonitorType.PING, name=name, hostname=hostname,
                        interval=60, maxretries=2, **notify)
        added += 1
        print(f"[seed]   + {name}", flush=True)

    # Declarative (Kenny, 2026-09-27): a monitor no file declares is removed,
    # a hand-made one included. The F158 shape (a monitor for a stack that is
    # gone, red or green forever) is what this removes.
    #
    # Only when there is a list to compare against. Without the generated
    # file, "not in the fleet" means "the file was missing", and on the first
    # live run that produced eleven warnings about stacks that all exist
    # (F175). Absent data is not the same as an empty answer.
    desired = {n: url for n, url, _ in APPLICATION_MONITORS}
    desired.update({n: host for n, host in host_monitors})
    monitors = api.get_monitors()
    to_tag, to_delete, refused, to_fix = plan_owned(monitors, desired, bool(have_generated_list))
    if to_tag:
        tag_id = ensure_owner_tag(api)
        for m in to_tag:
            api.add_monitor_tag(tag_id=tag_id, monitor_id=m["id"], value="")
    fixed = []
    for m, want in to_fix:
        field = "url" if m.get("url") else "hostname"
        api.edit_monitor(m["id"], **{field: want})
        fixed.append(m["name"])
        print(f"[seed]   ~ {m['name']} now points at {want}", flush=True)
    removed = []
    for m in to_delete:
        api.delete_monitor(m["id"])
        removed.append(m["name"])
        print(f"[seed]   - {m['name']} (no file declares it)", flush=True)
    if refused:
        print(f"[seed] WARN: {refused}", flush=True)
    # Left over only when removal was refused: reported for the fleet check.
    stale = []
    if have_generated_list and refused is not None:
        stale = sorted(m["name"] for m in monitors if m["name"] not in desired)
    for name in stale:
        print(f"[seed] WARN: '{name}' is declared nowhere and was not removed: "
              + (refused or ""), flush=True)

    print(f"[seed] {added} added, {skipped} already existed, "
          f"{len(fixed)} corrected, {len(removed)} removed, {len(stale)} stale", flush=True)

    # The verdict, written where something other than a human reading
    # container logs can find it.
    #
    # Kenny found the first real stale monitor on 2026-09-02 by noticing ping
    # errors on a Grafana dashboard — a drill container that had been
    # destroyed hours earlier and was still being pinged every minute. The
    # seeder had been saying so in its own log since the moment it happened,
    # and nothing read that log. A warning nobody reads is the same as no
    # warning; the nightly fleet check reads this file instead.
    status = {
        "at": int(time.time()),
        "added": added,
        "skipped": skipped,
        "stale": stale,
        "removed": removed,
        "corrected": fixed,
        "refused": refused,
        "judged": bool(have_generated_list),
        "almanac_notification": almanac_state,
        "ha_notification": ha_state,
    }
    try:
        path = env("STATUS_FILE", "/config/last-seed.json")
        tmp = path + ".tmp"
        with open(tmp, "w") as fh:
            json.dump(status, fh)
        os.replace(tmp, path)
    except OSError as exc:
        # Never fatal: this file is a report about the run, not part of it.
        print(f"[seed] WARN: could not write the status file: {exc}", flush=True)


def next_sleep(consecutive_errors, interval):
    """Seconds until the next round.

    A round that failed is retried after 30 seconds, up to ten times in a
    row, before the normal interval applies again. On 2026-09-27 a deploy
    recreated Kuma and this seeder together; the first round found Kuma not
    listening yet and then slept a whole hour, so nothing was seeded and the
    deploy's service check failed.
    """
    if 1 <= consecutive_errors <= 10:
        return 30
    return interval


def main():
    url = env("KUMA_URL")
    user = env("KUMA_USER")
    password = env("KUMA_PASSWORD")
    monitors_file = env("HOST_MONITORS_FILE", "/config/host-monitors.json")
    interval = int(env("SEED_INTERVAL_SECONDS", "3600"))

    errors = 0
    while True:
        try:
            api = UptimeKumaApi(url)
            try:
                api.login(user, password)
                monitors, had_list = load_host_monitors(monitors_file)
                seed_once(api, monitors, had_list)
                errors = 0
            finally:
                api.disconnect()
        except Exception as e:  # noqa: BLE001 — a loop that dies stops watching
            # Uptime Kuma restarting, a network blip, a changed password: all
            # of them are worth one loud line and another try. Exiting here
            # would leave every future stack unwatched, and the container
            # would be counted as "not running" by the deploy verification.
            print(f"[seed] ERROR: {type(e).__name__}: {e}", flush=True)
            errors += 1
        time.sleep(next_sleep(errors, interval))


if __name__ == "__main__":
    main()
