services:
  vikunja:
    image: vikunja/vikunja:latest
    container_name: vikunja
    env_file:
      - .env
    environment:
      - TZ=Europe/Brussels
    restart: unless-stopped
    ports:
      - "3456:3456"
    volumes:
      - /opt/gitops/stacks/todo/vikunja-config:/config
      - /opt/gitops/stacks/todo/vikunja-config/files:/app/vikunja/files
      - /opt/gitops/stacks/todo/vikunja-config/db:/db
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.homelab.backup.pause=true"
      - "traefik.enable=true"
      - "traefik.http.routers.vikunja.rule=Host(\"todo.kp-soft.dev\") || Host(\"todo\") || Host(\"vikunja\")"
      - "traefik.http.services.vikunja.loadbalancer.server.port=3456"
