networks:
  paperless_network:
    name: paperless_network
    external: true

services:
  broker:
    image: docker.io/library/redis:7
    container_name: paperless-broker
    restart: unless-stopped
    volumes:
      - /appdata/paperless/redisdata:/data
    networks:
      - paperless_network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.homelab.backup.pause=true"
