version: 1
stack_name: todo
vmid: 111
hostname: 111-app-todo
hwaddr: 02:ef:38:83:01:dd
tags: []
deploy:
  enabled: false
  activated_at: null
  last_applied_hash: 2266843ef7399a80cfbe8a7e9169b29bbc600df183e08be54a9107ea25374a1c
  last_applied_at: '1781636235'
  last_applied_apps:
    promtail: 0f841453209a2174881095df6d25bc0a9a6f003f7185dcbaf2dca332c84e2bbf
    vikunja: 3b0ecb2be0a20d2b2ef1704126c19f6b9ebcc1e2c295d376d8e7a23fc249881f
    watchtower: 965653dcbbe076bafc59779692ace7cd344d1205d42044cfa2d281f7a18da892
network:
  bridge: vmbr0
  ip_mode: static
  reserved_ipv4: 10.10.10.11
  cidr: 24
  gateway: 10.10.10.1
  vlan_tag: 10
  firewall: false
  ip_mode_v6: null
boot:
  autostart: true
  order: 90
resources:
  cores: 1
  cpu_limit: null
  cpu_units: 1024
  memory_mb: 512
  swap_mb: 512
  disk_gb: 5
storage:
  rootfs_pool: local-lvm
  host_path: /opt/appdata/todo
  mount_point: /appdata
  appdata_backup: true
  appdata_read_only: false
lxc:
  template: debian-12-standard 12.12-1 amd64
  unprivileged: true
  timezone: host
  features:
  - nesting=1
hardware:
  tun_device: null
host_management:
  managed: true
  protection: false
mounts:
- name: promtail-config
  source: /opt/appdata/todo/promtail-config
  target: /appdata/promtail-config
- name: vikunja-config
  source: /opt/appdata/todo/vikunja-config
  target: /appdata/vikunja-config
