version: 1
stack_name: todo
vmid: 111
hostname: 111-app-todo
hwaddr: 02:ef:38:83:01:dd
tags: []
deploy:
  enabled: true
  activated_at: '1781622688'
  last_applied_hash: 968efdd43fe8cca8efaece002f2020a26bd3ea59535dece8e6a480e320a75b00
  last_applied_at: '1781622760'
  last_applied_apps:
    promtail: 220334faf2e0acd92a48a22a6f3280c4bc2131a17439951a4f8a0589a67e78c6
    traefik: 4090dc5cf140b9b3389d2bc4a70887bfe32e0524c2273be3f8b8b6ab58532a79
    vikunja: 83b72ae2d8b1ed4cf46d310e2a716039a277c81ba793ec2e45901ee3d147b1f5
    watchtower: 965653dcbbe076bafc59779692ace7cd344d1205d42044cfa2d281f7a18da892
network:
  bridge: vmbr0
  ip_mode: static
  reserved_ipv4: 10.10.10.11
  cidr: 24
  gateway: 10.10.10.1
  vlan_tag: 10
  firewall: false
  ip_mode_v6: null
boot:
  autostart: true
  order: 90
resources:
  cores: 1
  cpu_limit: null
  cpu_units: 1024
  memory_mb: 512
  swap_mb: 512
  disk_gb: 5
storage:
  rootfs_pool: local-lvm
  host_path: /opt/appdata/todo
  mount_point: /appdata
  appdata_backup: true
  appdata_read_only: false
lxc:
  template: debian-12-standard 12.12-1 amd64
  unprivileged: true
  timezone: host
  features:
  - nesting=1
hardware:
  tun_device: null
host_management:
  managed: true
  protection: false
mounts:
- name: promtail-config
  source: /opt/appdata/todo/promtail-config
  target: /appdata/promtail-config
- name: traefik-config
  source: /opt/appdata/todo/traefik-config
  target: /appdata/traefik-config
- name: vikunja-config
  source: /opt/appdata/todo/vikunja-config
  target: /appdata/vikunja-config
