services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    hostname: syncthing-hub
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /appdata/synctest/synctest-config:/var/syncthing
    ports:
      - "8384:8384"       # web GUI (via traefik / LAN only)
      - "22000:22000/tcp" # sync protocol
      - "22000:22000/udp" # sync protocol (QUIC)
      - "21027:21027/udp" # local discovery
    restart: unless-stopped
    labels:
      - com.homelab.backup.pause=true
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - synctest_net

networks:
  synctest_net:
    external: true
    name: synctest_net
