services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower-media
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --label-enable
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
