version: 1
stack_name: cloudflared
vmid: 109
hostname: 109-app-cloudflared
hwaddr: 02:10:2b:c3:b8:9e
tags: []
deploy:
  enabled: true
  activated_at: '1781624810'
  last_applied_hash: 177d28efbc73cbfe943f22aa269f505bd5fabcbf62c6ff9af345c14b4f97a0af
  last_applied_at: '1781624879'
  last_applied_apps:
    cloudflared: 97d77d49f49ca43c6b841ea6692a4798612bcb7a436a593325b5483e2d523502
    promtail: e88ba38bde1441f265c6a5dbe95a51a6f40295ee55371ec3406a85257e3b7aa6
    watchtower: bcd830a76375a36846d25b8dc67a522e0bc9e094559c9bef77f7696666dd4fd4
network:
  bridge: vmbr0
  ip_mode: static
  reserved_ipv4: 10.10.10.9
  cidr: 24
  gateway: 10.10.10.1
  vlan_tag: 10
  firewall: false
  ip_mode_v6: null
boot:
  autostart: true
  order: 90
resources:
  cores: 1
  cpu_limit: null
  cpu_units: 1024
  memory_mb: 512
  swap_mb: 512
  disk_gb: 4
storage:
  rootfs_pool: local-lvm
  host_path: /opt/appdata/cloudflared
  mount_point: /appdata
  appdata_backup: true
  appdata_read_only: false
lxc:
  template: debian-12-standard 12.12-1 amd64
  unprivileged: true
  timezone: host
  features:
  - nesting=1
hardware:
  tun_device: null
host_management:
  managed: true
  protection: false
mounts:
- name: cloudflared-config
  source: /opt/appdata/cloudflared/cloudflared-config
  target: /appdata/cloudflared-config
