version: 1
stack_name: cloudflared
vmid: 109
hostname: 109-app-cloudflared
hwaddr: 02:10:2b:c3:b8:9e
tags: []
deploy:
  enabled: true
  activated_at: '1781632003'
  last_applied_hash: 043f64d7411ccabe290e53172d5d15be8d341f65b2d070d8452e3b613eb7ef8e
  last_applied_at: '1781632050'
  last_applied_apps:
    cloudflared: 0f574663e88f6acb704c16c66e3c56c1b9bc5e59ca4d45c1b3914293f6eac444
    promtail: 1ab75909f13b7e94f11f15fdfabd5b4efed90d788c97f760b177538682715100
    watchtower: bcd830a76375a36846d25b8dc67a522e0bc9e094559c9bef77f7696666dd4fd4
network:
  bridge: vmbr0
  ip_mode: static
  reserved_ipv4: 10.10.10.9
  cidr: 24
  gateway: 10.10.10.1
  vlan_tag: 10
  firewall: false
  ip_mode_v6: null
boot:
  autostart: true
  order: 90
resources:
  cores: 1
  cpu_limit: null
  cpu_units: 1024
  memory_mb: 512
  swap_mb: 512
  disk_gb: 4
storage:
  rootfs_pool: local-lvm
  host_path: /opt/appdata/cloudflared
  mount_point: /appdata
  appdata_backup: true
  appdata_read_only: false
lxc:
  template: debian-12-standard 12.12-1 amd64
  unprivileged: true
  timezone: host
  features:
  - nesting=1
hardware:
  tun_device: null
host_management:
  managed: true
  protection: false
mounts:
- name: cloudflared-config
  source: /opt/appdata/cloudflared/cloudflared-config
  target: /appdata/cloudflared-config
