version: 1
stack_name: cloudflared
vmid: 109
hostname: 109-app-cloudflared
hwaddr: 02:10:2b:c3:b8:9e
tags: []
deploy:
  enabled: true
  activated_at: '1781337942'
network:
  bridge: vmbr0
  ip_mode: static
  reserved_ipv4: 10.10.10.9
  cidr: 24
  gateway: 10.10.10.1
  vlan_tag: 10
  firewall: false
  ip_mode_v6: null
boot:
  autostart: true
  order: 90
resources:
  cores: 1
  cpu_limit: null
  cpu_units: 1024
  memory_mb: 512
  swap_mb: 512
  disk_gb: 4
storage:
  rootfs_pool: local-lvm
  host_path: /opt/appdata/cloudflared
  mount_point: /appdata
  appdata_backup: true
  appdata_read_only: false
lxc:
  template: debian-12-standard 12.12-1 amd64
  unprivileged: true
  timezone: host
  features:
  - nesting=1
hardware:
  tun_device: null
host_management:
  managed: true
  protection: false
mounts:
- name: cloudflared-config
  source: /opt/appdata/cloudflared/cloudflared-config
  target: /appdata/cloudflared-config
