//! Pure decisions: no I/O, no clock, no network (arch-crates).

pub mod access;
pub mod actions;
pub mod actions_cli;
pub mod actions_config;
pub mod actions_progress;
pub mod applyview;
pub mod asks;
pub mod config;
pub mod credentials;
pub mod drift;
pub mod drive;
pub mod driveedit;
pub mod drivelive;
pub mod editplan;
pub mod fleet;
pub mod fwmatrix;
pub mod guests;
pub mod hostsettings;
pub mod hostversion;
pub mod logs;
pub mod newstack;
pub mod notify;
pub mod schedule;
pub mod stackedit;
pub mod templates;
pub mod textdiff;
pub mod yamledit;
