server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://${LOKI_IP}:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          host: paperless
          __path__: /var/log/*log

  - job_name: docker
    pipeline_stages:
      - docker: {}
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          host: paperless
          __path__: /var/lib/docker/containers/*/*log

  - job_name: node_sync
    static_configs:
      - targets:
          - localhost
        labels:
          job: node_sync
          host: paperless
          __path__: /var/log/node-sync.log
    pipeline_stages:
      - logfmt:
          mapping:
            ts:
            level:
            stack:
            app:
      - labels:
          level:
          stack:
          app:
      - timestamp:
          source: ts
          format: RFC3339
