networks:
  paperless_network:
    name: paperless_network
    external: true

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower-paperless
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --label-enable
    networks:
      - paperless_network
    restart: unless-stopped
