networks:
  paperless_network:
    name: paperless_network
    external: true

services:
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-webserver
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PAPERLESS_REDIS=redis://paperless-broker:6379
      - PAPERLESS_DBHOST=paperless-db
      - PAPERLESS_DBPORT=5432
      - USERMAP_UID=1000
      - USERMAP_GID=1000
      - PAPERLESS_URL=http://<IP_VAN_JE_PAPERLESS_LXC>:8000 # Optioneel, handig voor AI/API
    volumes:
      - /appdata/paperless/data:/usr/src/paperless/data
      - /appdata/paperless/media:/usr/src/paperless/media
      - /appdata/paperless/export:/usr/src/paperless/export
      - /appdata/paperless/consume:/usr/src/paperless/consume
    networks:
      - paperless_network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.homelab.backup.pause=true"
