services:
  promtail:
    image: grafana/promtail:latest
    container_name: promtail-downloader
    volumes:
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./config.yml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml -config.expand-env=true
    env_file:
      - .env
    restart: unless-stopped
