services:
  promtail:
    image: grafana/promtail:latest
    container_name: downloader-promtail
    restart: unless-stopped
    volumes:
      - /var/log:/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /appdata/promtail-config:/etc/promtail
    env_file:
      - .env
    command: -config.file=/etc/promtail/config.yml -config.expand-env=true
    labels:
      com.centurylinklabs.watchtower.enable: "true"
