// drive-reach (Kenny, 2026-10-03): the Live view control catalog, built
// from the declarations themselves (drivable.js `declare`) and the router's
// own address and redirect tables, never written by hand. The dashboard's
// server embeds the result (admin/src/core/drivecatalog.rs) and serves it,
// so `homelab ui list` and `homelab ui click`/`goto` check a name against
// the catalog of the dashboard version that is actually running.
//
//   node --import ./test/support/kp-register.mjs scripts/drivecatalog.mjs
//
// writes js/drivecatalog.json; test/drivecatalog.test.js fails (and with it
// the commit gate) when the file is not what this script builds from the
// tree, when a control is declared twice (`declare` throws while the pages
// load), or when a page marks an element with an id it never declared.
import { readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const JS = new URL("../js/", import.meta.url);

/** Every module of the dashboard but main.js (which mounts the app). */
function modules(dir = JS, prefix = "") {
  /** @type {string[]} */
  const out = [];
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (e.isDirectory())
      out.push(...modules(new URL(`${e.name}/`, dir), `${prefix}${e.name}/`));
    else if (e.name.endsWith(".js") && `${prefix}${e.name}` !== "main.js")
      out.push(`${prefix}${e.name}`);
  }
  return out.sort();
}

/**
 * The catalog, as the dashboard's code declares it now.
 * @returns {Promise<object>}
 */
export async function buildCatalog() {
  for (const m of modules()) await import(new URL(m, JS).href);
  const d = await import(new URL("drivable.js", JS).href);
  const r = await import(new URL("router.js", JS).href);
  const redirects = r.redirectTable();
  /** Where a control lives now, a row or stack as its placeholder. @param {any} c */
  const href = (c) => {
    if (c.at) {
      const at = c.at(c.row ?? "");
      if (at) return decodeURIComponent(at);
    }
    return r.pageHref(c.page) ?? redirects[c.page] ?? `/${c.page}`;
  };
  return {
    about:
      "Generated by admin/web/scripts/drivecatalog.mjs from the drivable.js declarations and router.js; never edit by hand.",
    controls: d.controls().map((/** @type {any} */ c) => d.entry(c, href)),
    fields: d.fields().map((/** @type {any} */ f) => ({
      id: f.id,
      page: f.page,
      what: f.what,
      was: f.was,
    })),
    addresses: [...r.DRIVABLE_PATHS].sort(),
    redirects,
    stack_slot: r.STACK_SLOT,
  };
}

/** The file's text for a catalog: stable, one trailing newline. */
export const catalogText = (/** @type {object} */ c) =>
  `${JSON.stringify(c, null, 2)}\n`;

export const CATALOG_FILE = fileURLToPath(new URL("drivecatalog.json", JS));

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(CATALOG_FILE, catalogText(await buildCatalog()));
  console.log(`wrote ${CATALOG_FILE}`);
}
