networks:
  paperless_network:
    name: paperless_network
    external: true

services:
  ai-assistant:
    image: clusterzx/paperless-ai:latest
    container_name: paperless-ai
    restart: unless-stopped
    ports:
      - "3002:3000" # Web UI van de Tagger
      - "8001:8000" # Web UI van de RAG/Search (Optioneel)
    environment:
      # Interne verbinding binnen het Docker netwerk
      - PAPERLESS_API_URL=http://paperless-webserver:8000/api
    env_file:
      - .env
    volumes:
      # De container eist een fysiek .env bestand op deze locatie voor zijn interne scripts
      - ./.env:/app/data/.env:ro
      - /appdata/paperless/ai-data:/app/data
    networks:
      - paperless_network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.homelab.backup.pause=true"
