services:
  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: seerr
    environment:
      - TZ=Europe/Brussels
    volumes:
      - /appdata/media/seerr/config:/app/config
    ports:
      - "5055:5055"
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.homelab.backup.pause=true"
      - "com.homelab.tag.watchtower=enabled"
      - "com.homelab.tag.traefik.subdomain=seerr"
      - "com.homelab.tag.gpu=disabled"
      - "com.homelab.tag.vpn=none"
      - "traefik.enable=true"
      - "traefik.http.routers.seerr.rule=Host(`seerr.${DOMAIN:-example.com}`)"
      - "traefik.http.services.seerr.loadbalancer.server.port=5055"
