services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    environment:
      - TZ=Europe/Brussels
    volumes:
      - /appdata/monitoring/loki/config:/loki
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.homelab.backup.pause=true"
      - "com.homelab.tag.watchtower=enabled"
      - "com.homelab.tag.traefik.subdomain=loki"
      - "com.homelab.tag.gpu=disabled"
      - "com.homelab.tag.vpn=none"
      - "traefik.enable=true"
      - "traefik.http.routers.loki.rule=Host(`loki.${DOMAIN:-example.com}`)"
      - "traefik.http.services.loki.loadbalancer.server.port=3100"
    restart: unless-stopped
