services:
  promtail:
    image: grafana/promtail:latest
    container_name: monitoring-promtail
    restart: unless-stopped
    volumes:
      - /var/log:/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /appdata/monitoring/promtail/config:/etc/promtail
    env_file:
      - .env
    command: -config.file=/etc/promtail/config.yml -config.expand-env=true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.homelab.tag.watchtower=enabled"
      - "com.homelab.tag.role=infra-promtail"
      - "com.homelab.tag.traefik.subdomain=none"
      - "com.homelab.tag.gpu=disabled"
      - "com.homelab.tag.vpn=none"
