services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    env_file:
      - .env
    environment:
      - TZ=Europe/Brussels
      - COLLECTIONS=crowdsecurity/nginx-proxy-manager
    volumes:
      - /appdata/gateway/crowdsec/config:/etc/crowdsec
      - /appdata/gateway/crowdsec/data:/var/lib/crowdsec/data
      - /appdata/gateway/nginx-proxy-manager/data/logs:/var/log/npm:ro
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.homelab.backup.pause=true"
      - "com.homelab.tag.watchtower=enabled"
      - "com.homelab.tag.traefik.subdomain=none"
      - "com.homelab.tag.gpu=disabled"
      - "com.homelab.tag.vpn=none"
