services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    env_file:
      - .env
    environment:
      - TZ=Europe/Brussels
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_ADDRESSES=10.14.0.2/32
      - SERVER_HOSTNAMES=ch-zur.prod.surfshark.com
      - HEALTH_TARGET_ADDRESSES=1.1.1.1:443,8.8.8.8:443
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO /dev/null http://127.0.0.1:9999" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.homelab.backup.pause=true"
      - "com.homelab.tag.watchtower=enabled"
      - "com.homelab.tag.traefik.subdomain=none"
      - "com.homelab.tag.gpu=disabled"
      - "com.homelab.tag.vpn=gluetun"
      - "com.homelab.tag.role=vpn-gateway"
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - WEBUI_PORT=8080
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
    volumes:
      - /appdata/downloader/qbittorrent/config:/config
      - /mnt/downloads:/downloads
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.homelab.backup.pause=true"
      - "com.homelab.tag.watchtower=enabled"
      - "com.homelab.tag.traefik.subdomain=qbit"
      - "com.homelab.tag.gpu=disabled"
      - "com.homelab.tag.vpn=gluetun"
    restart: unless-stopped
