networks:
  gateway_network:
    name: gateway_network
    external: true

services:
  cs-firewall-bouncer:
    image: crowdsecurity/cs-firewall-bouncer:latest
    container_name: cs-firewall-bouncer
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Europe/Brussels
    volumes:
      - ./config.yaml:/etc/crowdsec/cs-firewall-bouncer.yaml:ro
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - gateway_network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
